name: Custom Whatever Loader CI Deploy

on:
  push:
    paths:
      - "CustomWhateverLoader/**"
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  build-and-upload:
    name: Build
    runs-on: windows-2025

    steps:
      - name: Checkout Code
        uses: actions/checkout@v5
        with:
          sparse-checkout: |
            CustomWhateverLoader/
            Directory.Build.props
          sparse-checkout-cone-mode: false

      - name: Checkout Deps Stable
        uses: actions/checkout@v5
        with:
          path: stable
          ref: stable
          repository: gottyduke/Elin.Plugins.BuildDeps
          ssh-key: ${{ secrets.DEPS_DEPLOY_KEY }}

      - name: Checkout Deps Nightly
        uses: actions/checkout@v5
        with:
          path: nightly
          ref: nightly
          repository: gottyduke/Elin.Plugins.BuildDeps
          ssh-key: ${{ secrets.DEPS_DEPLOY_KEY }}

      - name: Check files
        run: |
          echo $(ls)

      - name: Setup DotNet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10
          cache: true
          cache-dependency-path: ${{ github.workspace }}\CustomWhateverLoader\packages.lock.json

      - name: Setup Packages
        run: dotnet restore ${{ github.workspace }}\CustomWhateverLoader\ --locked-mode

      - name: Build Stable
        env:
          ElinGamePath: ${{ github.workspace }}\stable
        run: |
          dotnet build ${{ github.workspace }}\CustomWhateverLoader\CustomWhateverLoader.csproj -o ${{ github.workspace }}\out\stable -c Debug --no-restore

      - name: Upload Artifact Stable
        uses: actions/upload-artifact@v4
        with:
          name: cwl-ci-builds-stable
          path: ${{ github.workspace }}\out\stable

      - name: Build Nightly
        env:
          ElinGamePath: ${{ github.workspace }}\nightly
        run: |
          dotnet build ${{ github.workspace }}\CustomWhateverLoader\CustomWhateverLoader.csproj -o ${{ github.workspace }}\out\nightly -c DebugNightly --no-restore

      - name: Upload Artifact Nightly
        uses: actions/upload-artifact@v4
        with:
          name: cwl-ci-builds-nightly
          path: ${{ github.workspace }}\out\nightly
